### ISSUE TITLE
License violation with Bass.Net!

### ISSUE THREAD

**Issue by radio42** [ycastonguay/MPfm#1]
It seems, that you have simply reverse engineered the Bass.Net library!
You code clearly showed, that you did that - comments are the same...method signatures are the save, private members are the same!

The Bass.Net license clearly indicated the following:

By using this software (BASS.NET), you agree to the following conditions:
1) The freeware version of BASS.NET API is distributed under the license of radio42 (see LICENSE.rtf).
2) The LICENSEE may not charge for or make any money with the software using the freeware version of BASS.NET.
3) It is prohibited to change any of the provided source code and ALL the files must at any time remain intact and unmodified.
4) You may not decompile, disassemble, reverse engineer or modify any part of BASS.NET.
5) The LICENSEE may ONLY distribute the DLL part of BASS.NET with your software (Bass.Net.dll), no other part of BASS.NET may be distributed.
6) You may not resell or sublicense BASS.NET.
7) A splash screen will appear every time at start-up (unless you obtained a valid Registration-Key).
8) You are NOT allowed to pass your personal Registration-Key to anyone at anytime!
Please note, that you also need to take care of all BASS modules and their respective rights.

You at least violated with 3 of the above conditions!

So please remove this work from GitHub! Otherwise I am forced to take appropriate action and might file a copyright violation...

THX
Bernd - radio42

**Comment by ycastonguay** [comment]
This issue has been corrected a while ago, as BASS.NET source code was checked-in by mistake. In short, I used ILSpy to extract some of the P/Invoke code and test the BASS library on Android (before BASS.NET for Android was released). I resolved the issue with Bernd quickly and am still able to use BASS.NET for this project.
